002 crud operations
Team6-CS3250/DataProject pull request #8
Opened 2022-03-08 19:24 UTC by bleuflame47

Trying to get up to date with master

2022-03-08 22:03 UTC, kuddlefishbwaa requested changes
Looking more into the file, the CSV file only hast 6000~ entries so we don't need to change the db table to something different

2022-03-08 22:06 UTC, kuddlefishbwaa commented on DataProject/DatabaseWarehouse.py
> -    def __init__(self, master, **kwargs):
I don't think that we should delete all of this work. It's the whole base that brings up the DB in a view window. /the replacement would only have a button of "What would you like to do?"

2022-03-08 22:07 UTC, kuddlefishbwaa commented on DataProject/Operations.py
> +        #  I'm getting an FileNotFoundError on the line below.  Any suggestions as to how to fix this?
Was this fixed? if so then we can delete that.

2022-03-10 17:43 UTC, closed without merging

2022-03-15 15:13 UTC, Stowne1 commented
Helped test and review code.